package graphqlhunter.burp;

import burp.api.montoya.http.HttpService;
import burp.api.montoya.http.message.HttpRequestResponse;
import burp.api.montoya.http.message.requests.HttpRequest;
import burp.api.montoya.http.message.responses.HttpResponse;
import burp.api.montoya.scanner.audit.issues.AuditIssue;
import burp.api.montoya.scanner.audit.issues.AuditIssueConfidence;
import burp.api.montoya.scanner.audit.issues.AuditIssueSeverity;
import burp.api.montoya.sitemap.SiteMap;
import graphqlhunter.GraphQLHunterJson;
import graphqlhunter.GraphQLHunterLogger;
import graphqlhunter.GraphQLHunterModels;
import graphqlhunter.auth.AuthRedactor;

import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public final class BurpIssuePublisher
{
    interface IssueFactory
    {
        AuditIssue create(
            String name,
            String detail,
            String remediation,
            String baseUrl,
            AuditIssueSeverity severity,
            AuditIssueConfidence confidence,
            String background,
            String remediationBackground,
            List<HttpRequestResponse> requestResponses
        );
    }

    interface RequestResponseBuilder
    {
        List<HttpRequestResponse> build(GraphQLHunterModels.ScanRequest request, GraphQLHunterModels.Finding finding);
    }

    private final SiteMap siteMap;
    private final GraphQLHunterLogger logger;
    private final AuthRedactor redactor = new AuthRedactor();
    private final IssueFactory issueFactory;
    private final RequestResponseBuilder requestResponseBuilder;

    public BurpIssuePublisher(SiteMap siteMap, GraphQLHunterLogger logger)
    {
        this.siteMap = siteMap;
        this.logger = logger;
        this.issueFactory = (name, detail, remediation, baseUrl, severity, confidence, background, remediationBackground, requestResponses) ->
            AuditIssue.auditIssue(
                name,
                detail,
                remediation,
                baseUrl,
                severity,
                confidence,
                background,
                remediationBackground,
                severity,
                requestResponses
            );
        this.requestResponseBuilder = (request, finding) -> List.of(defaultRequestResponse(request, finding));
    }

    BurpIssuePublisher(
        SiteMap siteMap,
        GraphQLHunterLogger logger,
        IssueFactory issueFactory,
        RequestResponseBuilder requestResponseBuilder
    )
    {
        this.siteMap = siteMap;
        this.logger = logger;
        this.issueFactory = issueFactory;
        this.requestResponseBuilder = requestResponseBuilder;
    }

    public int publish(GraphQLHunterModels.ScanRequest request, List<GraphQLHunterModels.Finding> findings)
    {
        if (request == null || request.url == null || request.url.isBlank() || findings == null || findings.isEmpty())
        {
            return 0;
        }
        int published = 0;
        for (GraphQLHunterModels.Finding finding : findings)
        {
            siteMap.add(toAuditIssue(request, finding));
            published++;
        }
        if (logger != null)
        {
            logger.info("Published " + published + " GraphQL Hunter findings to Burp issues.");
        }
        return published;
    }

    AuditIssue toAuditIssue(GraphQLHunterModels.ScanRequest request, GraphQLHunterModels.Finding finding)
    {
        GraphQLHunterModels.Finding safeFinding = redactor.sanitizeFinding(finding, java.util.Set.of());
        List<HttpRequestResponse> requestResponses = requestResponseBuilder.build(request, safeFinding);
        AuditIssueSeverity severity = mapSeverity(safeFinding.severity);
        AuditIssueConfidence confidence = mapConfidence(safeFinding.status);
        return issueFactory.create(
            safeFinding.title,
            issueDetail(request, safeFinding),
            safeFinding.remediation,
            request.url,
            severity,
            confidence,
            "Generated by the GraphQL Hunter Burp extension from an imported GraphQL request.",
            safeFinding.impact == null ? "" : safeFinding.impact,
            requestResponses
        );
    }

    private HttpRequestResponse defaultRequestResponse(GraphQLHunterModels.ScanRequest request, GraphQLHunterModels.Finding finding)
    {
        URI uri = URI.create(request.url);
        boolean secure = "https".equalsIgnoreCase(uri.getScheme());
        int port = uri.getPort() == -1 ? (secure ? 443 : 80) : uri.getPort();
        HttpService service = HttpService.httpService(uri.getHost(), port, secure);
        HttpRequest httpRequest = HttpRequest.httpRequest(service, rawHttpRequest(request, finding, uri));
        HttpResponse httpResponse = HttpResponse.httpResponse("HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n");
        return HttpRequestResponse.httpRequestResponse(httpRequest, httpResponse);
    }

    private String issueDetail(GraphQLHunterModels.ScanRequest request, GraphQLHunterModels.Finding finding)
    {
        StringBuilder detail = new StringBuilder();
        detail.append("<p><b>Scanner:</b> ").append(escape(finding.scanner)).append("<br>");
        detail.append("<b>Status:</b> ").append(escape(finding.status.name().toLowerCase(Locale.ROOT))).append("<br>");
        detail.append("<b>Severity:</b> ").append(escape(finding.severity.name())).append("</p>");
        appendSection(detail, "Description", finding.description);
        appendSection(detail, "Impact", finding.impact);
        appendSection(detail, "Evidence", GraphQLHunterJson.write(finding.evidence));
        appendSection(detail, "Proof of Concept", finding.proof);
        appendSection(detail, "Replay Request", rawHttpRequest(request, finding, URI.create(request.url)));
        return detail.toString();
    }

    private String rawHttpRequest(GraphQLHunterModels.ScanRequest request, GraphQLHunterModels.Finding finding, URI uri)
    {
        String path = uri.getRawPath() == null || uri.getRawPath().isBlank() ? "/graphql" : uri.getRawPath();
        if (uri.getRawQuery() != null && !uri.getRawQuery().isBlank())
        {
            path += "?" + uri.getRawQuery();
        }
        Map<String, String> headers = new LinkedHashMap<>(redactor.redactHeaders(request.headers, java.util.Set.of()));
        headers.putIfAbsent("Host", uri.getAuthority());
        headers.putIfAbsent("Content-Type", request.contentType == null || request.contentType.isBlank() ? "application/json" : request.contentType);
        String body = preservedBody(request, finding);
        headers.put("Content-Length", String.valueOf(body.getBytes(StandardCharsets.UTF_8).length));

        StringBuilder builder = new StringBuilder();
        builder.append(request.method == null || request.method.isBlank() ? "POST" : request.method.toUpperCase(Locale.ROOT))
            .append(' ')
            .append(path)
            .append(" HTTP/1.1\r\n");
        headers.forEach((key, value) -> builder.append(key).append(": ").append(value).append("\r\n"));
        builder.append("\r\n").append(body);
        return builder.toString();
    }

    private Object requestPayload(GraphQLHunterModels.ScanRequest request, GraphQLHunterModels.Finding finding)
    {
        String candidate = firstNonBlank(finding.requestSnippet, finding.proof, request.rawBody);
        Object parsed = tryParseJson(candidate);
        if (parsed instanceof Map<?, ?> map && (map.containsKey("query") || map.containsKey("variables") || map.containsKey("operationName")))
        {
            return redactor.redactObject(parsed, null);
        }
        if (parsed instanceof List<?>)
        {
            return redactor.redactObject(parsed, null);
        }

        LinkedHashMap<String, Object> payload = new LinkedHashMap<>();
        payload.put("query", firstNonBlank(finding.requestSnippet, finding.proof, request.query));
        payload.put("variables", redactor.redactObject(request.variables, null));
        if (request.operationName != null && !request.operationName.isBlank())
        {
            payload.put("operationName", request.operationName);
        }
        return payload;
    }

    private String preservedBody(GraphQLHunterModels.ScanRequest request, GraphQLHunterModels.Finding finding)
    {
        if (request.rawBody != null && !request.rawBody.isBlank()
            && (request.batch
            || (request.contentType != null && (request.contentType.toLowerCase(Locale.ROOT).contains("multipart/form-data")
            || request.contentType.toLowerCase(Locale.ROOT).contains("application/graphql")))))
        {
            return redactor.redactText(request.rawBody);
        }
        return GraphQLHunterJson.write(requestPayload(request, finding));
    }

    private Object tryParseJson(String value)
    {
        if (value == null || value.isBlank())
        {
            return null;
        }
        String trimmed = value.trim();
        if (!(trimmed.startsWith("{") || trimmed.startsWith("[")))
        {
            return null;
        }
        try
        {
            return GraphQLHunterJson.mapper().readValue(trimmed, Object.class);
        }
        catch (Exception ignored)
        {
            return null;
        }
    }

    private String firstNonBlank(String... values)
    {
        for (String value : values)
        {
            if (value != null && !value.isBlank())
            {
                return value;
            }
        }
        return "";
    }

    private AuditIssueSeverity mapSeverity(GraphQLHunterModels.FindingSeverity severity)
    {
        return switch (severity)
        {
            case CRITICAL, HIGH -> AuditIssueSeverity.HIGH;
            case MEDIUM -> AuditIssueSeverity.MEDIUM;
            case LOW -> AuditIssueSeverity.LOW;
            case INFO -> AuditIssueSeverity.INFORMATION;
        };
    }

    private AuditIssueConfidence mapConfidence(GraphQLHunterModels.FindingStatus status)
    {
        return switch (status)
        {
            case CONFIRMED -> AuditIssueConfidence.CERTAIN;
            case POTENTIAL -> AuditIssueConfidence.FIRM;
            case MANUAL_REVIEW -> AuditIssueConfidence.TENTATIVE;
        };
    }

    private void appendSection(StringBuilder builder, String title, String value)
    {
        if (value == null || value.isBlank() || "null".equals(value))
        {
            return;
        }
        builder.append("<h3>").append(escape(title)).append("</h3><pre>").append(escape(value)).append("</pre>");
    }

    private String escape(String text)
    {
        if (text == null)
        {
            return "";
        }
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#x27;");
    }
}
